// Generated by scripts/check-public-api.mjs.
// This file records every local declaration reachable from the PPTX public entry.
// Do not edit by hand.

// --- file: pptx.d.ts ---
export interface ArrowEnd {
    type: string;
    w: string;
    len: string;
}
export function autoResize(render: (width: number, height: number) => void | Promise<void>, element: Element, opts?: AutoResizeOptions): () => void;
export interface AutoResizeOptions {
    pauseWhenHidden?: boolean;
}
export interface Bevel3d {
    w: number;
    h: number;
    prst: string;
}
export interface BlipBullet {
    type: 'blip';
    imagePath: string;
    mimeType: string;
    sizePct: number | null;
    sizePts?: number;
}
export function buildPptxHighlightLayer(layer: HTMLDivElement, runs: PptxTextRunInfo[], matches: PptxHighlightMatch[], cssWidth: number, cssHeight: number, measureForFont: (font: string) => (s: string) => number, colors?: PptxHighlightColors): void;
export function buildPptxTextLayer(layer: HTMLDivElement, runs: PptxTextRunInfo[], cssWidth: number, cssHeight: number, onHyperlinkClick?: (target: HyperlinkTarget) => void, slideIndex?: number): void;
export type Bullet = Bullet__emitterCollision1 | BlipBullet;
type Bullet__emitterCollision1 = {
    type: 'none';
} | {
    type: 'inherit';
} | {
    type: 'char';
    char: string;
    color: string | null;
    sizePct: number | null;
    sizePts?: number;
    fontFamily: string | null;
} | {
    type: 'autoNum';
    numType: string;
    startAt: number | null;
    color: string | null;
    sizePct?: number | null;
    sizePts?: number;
    fontFamily?: string | null;
};
export interface Camera3d {
    prst: string;
    fov?: number;
    zoom?: number;
    rot?: Rot3d;
}
export interface ChartDataLabelOverride {
    idx: number;
    text: string;
    position?: string;
    fontColor?: string;
    fontSizeHpt?: number;
    fontBold?: boolean;
    formatCode?: string;
    separator?: string;
    manualLayout?: ChartManualLayout;
    labelBox?: ChartLabelBox;
    showVal?: boolean;
    showCatName?: boolean;
    showSerName?: boolean;
    showPercent?: boolean;
    deleted?: boolean;
}
export interface ChartDataPointOverride {
    idx: number;
    color?: string;
    fillHidden?: boolean;
    lineColor?: string;
    lineWidthEmu?: number;
    lineDash?: string;
    lineHidden?: boolean;
    markerSymbol?: string;
    markerSize?: number;
    markerFill?: string;
    markerLine?: string;
    explosion?: number;
}
export interface ChartElement {
    type: 'chart';
    x: number;
    y: number;
    width: number;
    height: number;
    rotation: number;
    flipH: boolean;
    flipV: boolean;
    chart: ChartModel;
}
export interface ChartErrBars {
    dir: string;
    barType: string;
    plus: (number | null)[];
    minus: (number | null)[];
    noEndCap: boolean;
    color?: string;
    lineWidthEmu?: number;
    dash?: string;
}
export interface ChartexBoxSeries {
    name: string;
    chartexFormatIdx?: number | null;
    color?: string | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    chartexStyle?: ChartExElementStyle | null;
    valuesByCategory: number[][];
    meanMarker: boolean;
    meanLine: boolean;
    showOutliers: boolean;
    showNonoutliers: boolean;
    quartileMethod: string;
}
export interface ChartexBoxWhisker {
    categories: string[];
    series: ChartexBoxSeries[];
}
export interface ChartExElementStyle {
    fillPaints?: Array<SolidFill | GradientFill | PatternFill | null> | null;
    fillColors?: Array<string | null> | null;
    fillHidden?: boolean | null;
    fillNoStyle?: boolean | null;
    lineColors?: Array<string | null> | null;
    lineWidthEmu?: number | null;
    lineHidden?: boolean | null;
    lineNoStyle?: boolean | null;
    lineDash?: string | null;
    lineCap?: string | null;
    lineJoin?: string | null;
    fillColorIndex?: number | null;
    lineColorIndex?: number | null;
}
export interface ChartexSunburst {
    rows: ChartexSunburstRow[];
}
export interface ChartexSunburstRow {
    path: string[];
    size: number;
}
export interface ChartexTreemap {
    rows: ChartexSunburstRow[];
    parentLabelLayout?: string | null;
}
export interface ChartexHistogramBinning {
    binSize?: number | null;
    binCount?: number | null;
    intervalClosed?: 'l' | 'r' | null;
    underflow?: number | null;
    overflow?: number | null;
}
export interface ChartLabelBox {
    fill?: string;
    borderColor?: string;
    borderWidthEmu?: number;
}
export interface ChartManualLayout {
    xMode?: string;
    yMode?: string;
    wMode?: string;
    hMode?: string;
    layoutTarget?: string;
    x: number;
    y: number;
    w?: number;
    h?: number;
}
export interface ChartModel {
    chartType: ChartType;
    title: string | null;
    titlePresent?: boolean;
    categories: string[];
    series: ChartSeries[];
    chartTextBoxes?: ChartTextBox[] | null;
    varyColors?: boolean | null;
    showDataLabels: boolean;
    valMin: number | null;
    valMax: number | null;
    catAxisTitle: string | null;
    valAxisTitle: string | null;
    catAxisHidden: boolean;
    valAxisHidden: boolean;
    catAxisLineHidden: boolean;
    valAxisLineHidden: boolean;
    plotAreaBg: string | null;
    chartBg: string | null;
    showLegend: boolean;
    legendPos: 'r' | 'l' | 't' | 'b' | 'tr' | null;
    catAxisCrossBetween: 'between' | 'midCat' | string;
    valAxisMajorTickMark: 'cross' | 'out' | 'in' | 'none' | string;
    catAxisMajorTickMark: 'cross' | 'out' | 'in' | 'none' | string;
    valAxisMinorTickMark?: 'cross' | 'out' | 'in' | 'none' | string | null;
    catAxisMinorTickMark?: 'cross' | 'out' | 'in' | 'none' | string | null;
    titleFontSizeHpt: number | null;
    titleFontColor: string | null;
    titleFontFace: string | null;
    catAxisFontSizeHpt: number | null;
    valAxisFontSizeHpt: number | null;
    catAxisFontColor?: string | null;
    valAxisFontColor?: string | null;
    dataLabelFontSizeHpt: number | null;
    dataLabelFontBold?: boolean | null;
    subtotalIndices: number[];
    legendManualLayout?: LegendManualLayout | null;
    valAxisFormatCode?: string | null;
    barGapWidth?: number | null;
    barOverlap?: number | null;
    dataLabelPosition?: string | null;
    dataLabelFontColor?: string | null;
    dataLabelFormatCode?: string | null;
    titleFontBold?: boolean | null;
    catAxisFontBold?: boolean | null;
    valAxisFontBold?: boolean | null;
    catAxisTitleFontSizeHpt?: number | null;
    catAxisTitleFontBold?: boolean | null;
    catAxisTitleFontColor?: string | null;
    catAxisTitleRotation?: number | null;
    catAxisTitleVerticalMode?: 'horz' | 'vert' | 'vert270' | 'wordArtVert' | 'eaVert' | 'mongolianVert' | 'wordArtVertRtl' | null;
    catAxisTitleManualLayout?: ChartManualLayout | null;
    valAxisTitleFontSizeHpt?: number | null;
    valAxisTitleFontBold?: boolean | null;
    valAxisTitleFontColor?: string | null;
    valAxisTitleRotation?: number | null;
    valAxisTitleVerticalMode?: 'horz' | 'vert' | 'vert270' | 'wordArtVert' | 'eaVert' | 'mongolianVert' | 'wordArtVertRtl' | null;
    valAxisTitleManualLayout?: ChartManualLayout | null;
    catAxisFontFace?: string | null;
    valAxisFontFace?: string | null;
    catAxisTitleFontFace?: string | null;
    valAxisTitleFontFace?: string | null;
    dataLabelFontFace?: string | null;
    legendFontFace?: string | null;
    legendFontColor?: string | null;
    legendFontSizeHpt?: number | null;
    legendFontBold?: boolean | null;
    themeMajorFontLatin?: string | null;
    themeMinorFontLatin?: string | null;
    chartBorderColor?: string | null;
    chartBorderWidthEmu?: number | null;
    catAxisCrosses?: string | null;
    catAxisCrossesAt?: number | null;
    valAxisCrosses?: string | null;
    valAxisCrossesAt?: number | null;
    catAxisLineColor?: string | null;
    catAxisLineWidthEmu?: number | null;
    valAxisLineColor?: string | null;
    valAxisLineWidthEmu?: number | null;
    catAxisFormatCode?: string | null;
    catAxisMin?: number | null;
    catAxisMax?: number | null;
    titleManualLayout?: ChartManualLayout | null;
    plotAreaManualLayout?: ChartManualLayout | null;
    scatterStyle?: string | null;
    bubbleScale?: number | null;
    bubbleSizeRepresents?: 'area' | 'w' | null;
    showNegativeBubbles?: boolean | null;
    radarStyle?: string | null;
    secondaryValAxis?: SecondaryValueAxis | null;
    secondaryCatAxis?: SecondaryValueAxis | null;
    date1904?: boolean;
    holeSize?: number | null;
    firstSliceAngle?: number | null;
    dispBlanksAs?: string | null;
    valAxisMajorGridlines?: boolean | null;
    catAxisMajorGridlines?: boolean | null;
    valAxisGridlineColor?: string | null;
    valAxisGridlineWidthEmu?: number | null;
    valAxisGridlineDash?: string | null;
    catAxisGridlineColor?: string | null;
    catAxisGridlineWidthEmu?: number | null;
    catAxisGridlineDash?: string | null;
    valAxisMinorGridlines?: boolean | null;
    valAxisMinorGridlineColor?: string | null;
    valAxisMinorGridlineWidthEmu?: number | null;
    valAxisMinorGridlineDash?: string | null;
    catAxisMinorGridlines?: boolean | null;
    catAxisMinorGridlineColor?: string | null;
    catAxisMinorGridlineWidthEmu?: number | null;
    catAxisMinorGridlineDash?: string | null;
    valAxisMajorUnit?: number | null;
    valAxisMinorUnit?: number | null;
    catAxisMajorUnit?: number | null;
    catAxisMinorUnit?: number | null;
    valAxisLogBase?: number | null;
    valAxisOrientation?: 'minMax' | 'maxMin' | string | null;
    catAxisOrientation?: 'minMax' | 'maxMin' | string | null;
    catAxisTickLabelPos?: string | null;
    catAxisTickLabelSkip?: number | null;
    catAxisTickMarkSkip?: number | null;
    valAxisTickLabelPos?: string | null;
    catAxisLabelRotation?: number | null;
    stockHiLowLines?: boolean | null;
    stockHiLowLineColor?: string | null;
    stockUpDownBars?: boolean | null;
    chartexBox?: ChartexBoxWhisker | null;
    chartexSunburst?: ChartexSunburst | null;
    chartexTreemap?: ChartexTreemap | null;
    chartexHistogramBinning?: ChartexHistogramBinning | null;
    chartexAccents?: string[] | null;
    chartexColorPalette?: Array<string | null> | null;
    chartexColorStyleMethod?: string | null;
    chartexDataPointStyle?: ChartExElementStyle | null;
    chartexDataPointLineStyle?: ChartExElementStyle | null;
    chartexDataPointMarkerStyle?: ChartExElementStyle | null;
    chartexMarkerSizePt?: number | null;
    chartexMarkerSymbol?: string | null;
    chartexConnectorLines?: boolean | null;
}
export interface ChartRect {
    x: number;
    y: number;
    w: number;
    h: number;
}
export interface ChartSeries {
    name: string;
    chartexFormatIdx?: number | null;
    color: string | null;
    fillPattern?: PatternFill | null;
    chartexStyle?: ChartExElementStyle | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    values: (number | null)[];
    dataPointColors?: (string | null)[] | null;
    dataLabelColors?: (string | null)[] | null;
    labelColor?: string | null;
    seriesType?: string | null;
    useSecondaryAxis?: boolean | null;
    categories?: string[] | null;
    showMarker?: boolean | null;
    valFormatCode?: string | null;
    catFormatCode?: string | null;
    catFormatCodes?: (string | null)[] | null;
    markerSymbol?: string | null;
    markerSize?: number | null;
    markerFill?: string | null;
    markerLine?: string | null;
    dataPointOverrides?: ChartDataPointOverride[] | null;
    dataLabelOverrides?: ChartDataLabelOverride[] | null;
    seriesDataLabels?: ChartSeriesDataLabels | null;
    errBars?: ChartErrBars[] | null;
    bubbleSizes?: (number | null)[] | null;
    smooth?: boolean | null;
    trendLines?: ChartTrendline[] | null;
    lineHidden?: boolean | null;
}
export interface ChartSeriesDataLabels {
    showVal: boolean;
    showCatName: boolean;
    showSerName: boolean;
    showPercent: boolean;
    position?: string;
    fontColor?: string;
    formatCode?: string;
    separator?: string;
    fontBold?: boolean;
    fontSizeHpt?: number;
    labelBox?: ChartLabelBox;
    showLeaderLines?: boolean;
    leaderLineColor?: string;
    leaderLineWidthEmu?: number;
}
export interface ChartTextBox {
    x: number;
    y: number;
    w: number;
    h: number;
    paragraphs: ChartTextParagraph[];
    verticalAnchor?: 't' | 'ctr' | 'b' | 'just' | 'dist' | string | null;
    wrap?: 'none' | 'square' | string | null;
    lIns?: number;
    tIns?: number;
    rIns?: number;
    bIns?: number;
}
export interface ChartTextParagraph {
    runs: ChartTextRun[];
    align?: 'l' | 'ctr' | 'r' | 'just' | 'dist' | string | null;
}
export interface ChartTextRun {
    text: string;
    fontSizeHpt?: number | null;
    bold?: boolean | null;
    color?: string | null;
    fontFace?: string | null;
}
export interface ChartTrendline {
    trendlineType: string;
    order?: number | null;
    period?: number | null;
    forward?: number | null;
    backward?: number | null;
    intercept?: number | null;
    dispRSqr?: boolean | null;
    dispEq?: boolean | null;
    labelManualLayout?: ChartManualLayout | null;
    labelText?: string | null;
    labelFontSizeHpt?: number | null;
    labelFontBold?: boolean | null;
    labelFontColor?: string | null;
    labelFontFace?: string | null;
    labelTextAlign?: string | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    lineDash?: string | null;
    lineHidden?: boolean | null;
}
export type ChartType = 'line' | 'stackedLine' | 'stackedLinePct' | 'clusteredBar' | 'clusteredBarH' | 'stackedBar' | 'stackedBarH' | 'stackedBarPct' | 'stackedBarHPct' | 'area' | 'stackedArea' | 'stackedAreaPct' | 'pie' | 'doughnut' | 'scatter' | 'bubble' | 'radar' | 'waterfall' | 'stock' | 'boxWhisker' | 'sunburst' | 'treemap' | string;
export interface DimOptions {
    color: string;
    opacity: number;
}
export interface Duotone {
    clr1: string;
    clr2: string;
}
export interface EquationRun {
    type: 'math';
    nodes: MathNode[];
    display: boolean;
    fontSize?: number | null;
    color?: string | null;
}
type ExtensibleLiteral<Known extends string> = Known | (string & Record<never, never>);
export type Fill = SolidFill | NoFill | GradientFill | PatternFill | ImageFill;
export interface FillRect {
    l?: number;
    t?: number;
    r?: number;
    b?: number;
}
export interface FindHighlightColors {
    match?: string;
    active?: string;
}
export interface FindMatch<Loc = unknown> {
    matchIndex: number;
    text: string;
    location: Loc;
}
export interface FindMatchesOptions {
    caseSensitive?: boolean;
}
export interface Glow {
    color: string;
    alpha: number;
    radius: number;
}
export interface GradientFill {
    fillType: 'gradient';
    stops: GradientStop[];
    angle: number;
    gradType: string;
    scaled?: boolean;
    path?: 'shape' | 'circle' | 'rect' | string;
    fillToRect?: FillRect;
    tileRect?: FillRect;
    flip?: 'none' | 'x' | 'y' | 'xy' | string;
    rotWithShape?: boolean;
}
export interface GradientStop {
    position: number;
    color: string;
}
export type HiddenSlideMode = 'show' | 'skip' | 'dim';
export type HyperlinkTarget = {
    kind: 'external';
    url: string;
} | {
    kind: 'internal';
    ref: string;
    slideIndex?: number;
};
export interface ImageFill {
    fillType: 'image';
    imagePath: string;
    mimeType: string;
    fillRect?: FillRect;
    tile?: TileInfo;
    alpha?: number;
    duotone?: Duotone;
}
export function isOoxmlDecodedImageLimitError(error: unknown): error is OoxmlDecodedImageLimitError;
export interface LegendManualLayout {
    xMode?: string;
    yMode?: string;
    wMode?: string;
    hMode?: string;
    x: number;
    y: number;
    w: number;
    h: number;
}
export interface LightRig {
    rig: string;
    dir: string;
    rot?: Rot3d;
}
export interface LineBreak {
    type: 'break';
}
export type LoadOptions = LoadOptions__emitterCollision1 & {
    mode?: 'main' | 'worker';
};
interface LoadOptions__emitterCollision1 {
    useGoogleFonts?: boolean;
    password?: string;
    wasmUrl?: string | URL;
    maxZipEntryBytes?: number;
    resourceLimits?: OoxmlResourceLimits;
    debug?: boolean;
    onResourceMetrics?: (metrics: OoxmlResourceMetrics) => void;
    workerTimeoutMs?: number;
    math?: MathRenderer;
}
export interface MatchRunSlice {
    runIndex: number;
    start: number;
    end: number;
}
export interface MathAccent {
    kind: 'accent';
    char: string;
    base: MathNode[];
}
export interface MathArray {
    kind: 'array';
    rows: MathNode[][][];
    align: 'eq' | 'center' | 'left';
}
export interface MathBar {
    kind: 'bar';
    pos: 'top' | 'bot';
    base: MathNode[];
}
export interface MathBorderBox {
    kind: 'borderBox';
    hideTop?: boolean;
    hideBot?: boolean;
    hideLeft?: boolean;
    hideRight?: boolean;
    strikeH?: boolean;
    strikeV?: boolean;
    strikeBltr?: boolean;
    strikeTlbr?: boolean;
    base: MathNode[];
}
export interface MathBox {
    kind: 'box';
    base: MathNode[];
}
export interface MathDelimiter {
    kind: 'delimiter';
    begChar: string;
    endChar: string;
    items: MathNode[][];
}
export interface MathFraction {
    kind: 'fraction';
    num: MathNode[];
    den: MathNode[];
    bar?: boolean;
}
export interface MathFunc {
    kind: 'func';
    name: MathNode[];
    arg: MathNode[];
}
export interface MathGroup {
    kind: 'group';
    items: MathNode[];
}
export interface MathGroupChr {
    kind: 'groupChr';
    char: string;
    pos: 'top' | 'bot';
    base: MathNode[];
}
export interface MathLimit {
    kind: 'limit';
    base: MathNode[];
    lower?: MathNode[];
    upper?: MathNode[];
}
export interface MathNary {
    kind: 'nary';
    op: string;
    limLoc?: string;
    sub?: MathNode[];
    sup?: MathNode[];
    body: MathNode[];
}
export type MathNode = MathRun | MathFraction | MathScript | MathNary | MathDelimiter | MathRadical | MathLimit | MathArray | MathGroupChr | MathBar | MathAccent | MathFunc | MathGroup | MathPhant | MathSPre | MathBox | MathBorderBox;
export interface MathPhant {
    kind: 'phant';
    show: boolean;
    zeroWid?: boolean;
    zeroAsc?: boolean;
    zeroDesc?: boolean;
    base: MathNode[];
}
export interface MathRadical {
    kind: 'radical';
    index?: MathNode[];
    radicand: MathNode[];
}
export interface MathRenderer {
    loadMathJax(): Promise<void>;
    mathMLToSvg(mathml: string): Promise<MathSvg>;
}
export interface MathRun {
    kind: 'run';
    text: string;
    style: MathStyle;
}
export interface MathScript {
    kind: 'sup' | 'sub' | 'subSup';
    base: MathNode[];
    sup?: MathNode[];
    sub?: MathNode[];
}
export interface MathSPre {
    kind: 'sPre';
    sub: MathNode[];
    sup: MathNode[];
    base: MathNode[];
}
export type MathStyle = 'roman' | 'italic' | 'bold' | 'boldItalic';
export interface MathSvg {
    svg: string;
    widthEm: number;
    ascentEm: number;
    descentEm: number;
}
export interface MediaElement {
    type: 'media';
    x: number;
    y: number;
    width: number;
    height: number;
    rotation: number;
    flipH: boolean;
    flipV: boolean;
    mediaKind: 'audio' | 'video';
    posterPath: string;
    posterMimeType: string;
    mediaPath: string;
    mimeType: string;
}
export interface NoFill {
    fillType: 'none';
}
export class OoxmlDecodedImageLimitError extends RangeError {
    readonly metric: OoxmlDecodedImageLimitMetric;
    readonly limit: number;
    readonly observed: number;
    readonly code: 'ooxml-decoded-image-limit';
    constructor(metric: OoxmlDecodedImageLimitMetric, limit: number, observed: number);
}
export type OoxmlDecodedImageLimitMetric = 'image-pixels' | 'active-decoded-bytes';
export class OoxmlError extends Error {
    readonly code: OoxmlErrorCode;
    constructor(code: OoxmlErrorCode, message: string);
}
export type OoxmlErrorCode = 'encrypted' | 'invalid-password' | 'unsupported-encryption' | 'legacy-binary-format' | 'not-ooxml';
export type OoxmlErrorStage = 'container' | 'decompression' | 'parsing' | 'serialization' | 'layout' | 'rendering' | 'worker';
export type OoxmlFormat = 'docx' | 'xlsx' | 'pptx';
export type OoxmlResourceLimit = number | null;
export class OoxmlResourceLimitError extends Error {
    readonly code: 'ooxml-resource-limit';
    readonly details: OoxmlResourceLimitErrorDetails;
    constructor(message: string, details: OoxmlResourceLimitErrorDetails);
}
export interface OoxmlResourceLimitErrorDetails {
    readonly stage: OoxmlErrorStage;
    readonly violation: OoxmlResourceViolation;
}
export interface OoxmlResourceLimits {
    maxArchiveEntryBytes?: OoxmlResourceLimit;
    maxTotalInflatedBytes?: OoxmlResourceLimit;
    maxArchiveEntries?: OoxmlResourceLimit;
}
export type OoxmlResourceMetric = ExtensibleLiteral<'declared-inflated-bytes' | 'actual-inflated-bytes' | 'entry-count' | 'central-directory-bytes' | 'distinct-inflated-bytes' | 'bytes' | 'depth' | 'projected-bytes'>;
export interface OoxmlResourceMetrics {
    readonly schemaVersion: 1;
    readonly scope: 'load' | 'session';
    readonly format: OoxmlFormat;
    readonly mode: 'main' | 'worker' | 'node';
    readonly status: 'ok' | 'error';
    readonly sourceBytes?: number;
    readonly elapsedMs: number;
    readonly policy: Readonly<OoxmlResourcePolicySnapshot>;
    readonly usage?: OoxmlResourceUsageSnapshot;
    readonly checkpoints: readonly OoxmlResourceMetricsCheckpoint[];
    readonly outcome?: Readonly<Record<string, number>>;
    readonly error?: Readonly<{
        readonly code?: string;
        readonly stage?: string;
        readonly resource?: string;
        readonly metric?: string;
    }>;
}
export interface OoxmlResourceMetricsCheckpoint {
    readonly name: string;
    readonly elapsedMs: number;
    readonly usage?: OoxmlResourceUsageSnapshot;
}
export type OoxmlResourceName = ExtensibleLiteral<'archive' | 'archive-entry' | 'xml-event' | 'xml-context' | 'xml-tree' | 'worksheet-row' | 'worksheet-shell'>;
export interface OoxmlResourcePolicySnapshot {
    readonly maxArchiveEntryBytes: number | null;
    readonly maxTotalInflatedBytes: number | null;
    readonly maxArchiveEntries: number | null;
}
export interface OoxmlResourceUsageSnapshot {
    readonly archiveEntryCount: number;
    readonly declaredInflatedBytes: number;
    readonly largestInflatedEntryBytes?: number;
    readonly distinctInflatedBytes: number;
    readonly operationInflatedBytes: number;
}
export interface OoxmlResourceViolation {
    readonly format: OoxmlFormat;
    readonly operation: string;
    readonly resource: OoxmlResourceName;
    readonly metric: OoxmlResourceMetric;
    readonly part?: string;
    readonly limit: number;
    readonly observed: number;
    readonly configurable: boolean;
    readonly usage: OoxmlResourceUsageSnapshot;
}
export function openExternalHyperlink(url: string, allowed?: readonly string[], win?: Pick<Window, 'open'> | undefined): boolean;
export interface Paragraph extends Paragraph__emitterCollision1 {
    eaLnBrk: boolean;
    defTabSz?: number;
}
interface Paragraph__emitterCollision1 {
    alignment: string;
    marL: number;
    marR: number;
    indent: number;
    spaceBefore: number | null;
    spaceAfter: number | null;
    spaceLine: SpaceLine | null;
    lvl: number;
    bullet: Bullet__emitterCollision1;
    defFontSize: number | null;
    defColor: string | null;
    defBold: boolean | null;
    defItalic: boolean | null;
    defFontFamily: string | null;
    tabStops: TabStop[];
    rtl?: boolean;
    runs: TextRun[];
}
export type PathCmd = {
    cmd: 'moveTo';
    x: number;
    y: number;
} | {
    cmd: 'lineTo';
    x: number;
    y: number;
} | {
    cmd: 'cubicBezTo';
    x1: number;
    y1: number;
    x2: number;
    y2: number;
    x: number;
    y: number;
} | {
    cmd: 'quadBezTo';
    x1: number;
    y1: number;
    x: number;
    y: number;
} | {
    cmd: 'arcTo';
    wr: number;
    hr: number;
    stAng: number;
    swAng: number;
} | {
    cmd: 'close';
};
export interface PatternFill {
    fillType: 'pattern';
    fg: string;
    bg: string;
    preset: string;
}
export interface PictureElement {
    type: 'picture';
    x: number;
    y: number;
    width: number;
    height: number;
    rotation: number;
    flipH: boolean;
    flipV: boolean;
    imagePath: string;
    mimeType: string;
    svgImagePath?: string;
    intrinsicWidthPx?: number;
    intrinsicHeightPx?: number;
    stroke: Stroke | null;
    prstGeom?: string;
    prstAdjust?: number[];
    srcRect?: {
        l: number;
        t: number;
        r: number;
        b: number;
    };
    alpha?: number;
    duotone?: Duotone;
    custGeom?: PathCmd[][] | null;
    shadow?: Shadow;
    innerShadow?: Shadow;
    glow?: Glow;
    softEdge?: SoftEdge;
    reflection?: Reflection;
    scene3d?: Scene3d;
    sp3d?: Sp3d;
}
export interface PptxComment {
    author?: string;
    date?: string;
    text: string;
}
export interface PptxElementContext {
    readonly format: 'pptx';
    readonly kind: 'element';
    readonly slideIndex: number;
    readonly elementIndex: number;
    readonly origin: SlideElementOrigin | 'unknown';
    readonly elementType: SlideElement['type'];
    readonly point: PptxSlidePoint;
    readonly bounds: Readonly<{
        x: number;
        y: number;
        width: number;
        height: number;
        rotation: number;
        flipH: boolean;
        flipV: boolean;
    }>;
    readonly shapeId?: string;
    readonly name?: string;
    readonly geometry?: string;
    readonly text?: string;
    readonly mimeType?: string;
    readonly mediaKind?: 'audio' | 'video';
    readonly rowCount?: number;
    readonly columnCount?: number;
    readonly seriesCount?: number;
    readonly truncated: boolean;
    readonly truncationReasons: readonly 'text'[];
    readonly textCharacters: number;
    readonly maxTextCharacters: number;
}
export interface PptxElementContextOptions {
    readonly tolerance?: number;
    readonly maxTextCharacters?: number;
}
export type PptxHighlightColors = FindHighlightColors;
export interface PptxHighlightMatch {
    slices: MatchRunSlice[];
    active: boolean;
}
export interface PptxMatchLocation {
    slide: number;
}
export class PptxPresentation {
    static load(source: string | ArrayBuffer, opts?: LoadOptions): Promise<PptxPresentation>;
    get slideCount(): number;
    get slideWidth(): number;
    get slideHeight(): number;
    get mode(): 'main' | 'worker';
    getNotes(slideIndex: number): string | null;
    isHidden(slideIndex: number): boolean;
    getSlideIndexByPartName(partName: string): number | undefined;
    resolveInternalTarget(ref: string, currentIndex?: number): number | undefined;
    renderSlide(canvas: HTMLCanvasElement | OffscreenCanvas, slideIndex: number, opts?: RenderSlideOptions): Promise<void>;
    renderSlideToBitmap(slideIndex: number, opts?: RenderSlideToBitmapOptions): Promise<ImageBitmap>;
    collectSlideRuns(slideIndex: number, width?: number): Promise<PptxTextRunInfo[]>;
    getElementContextAt(slideIndex: number, point: PptxSlidePoint, options?: PptxElementContextOptions): Promise<PptxElementContext | null>;
    getMedia(mediaPath: string): Promise<Blob>;
    getImage(imagePath: string, mimeType: string): Promise<Blob>;
    getResourceMetrics(): Promise<OoxmlResourceMetrics>;
    toMarkdown(): Promise<string>;
    presentSlide(canvas: HTMLCanvasElement, slideIndex: number, opts?: PresentSlideOptions): Promise<PresentationHandle>;
    destroy(): void;
    private __privatePresence;
    private constructor();
}
export class PptxScrollViewer implements ZoomableViewer {
    static fromPresentation(container: HTMLElement, presentation: PptxPresentation, opts?: Omit<PptxScrollViewerOptions, keyof LoadOptions>): Omit<PptxScrollViewer, 'load'>;
    constructor(container: HTMLElement, opts?: PptxScrollViewerOptions);
    load(source: string | ArrayBuffer): Promise<void>;
    get slideCount(): number;
    relayout(): void;
    setScale(scale: number): void;
    getScale(): number;
    zoomIn(): void;
    zoomOut(): void;
    fitWidth(): void;
    fitPage(): void;
    scrollToSlide(index: number, opts?: {
        behavior?: 'auto' | 'smooth';
    }): void;
    findText(query: string, opts?: FindMatchesOptions): Promise<FindMatch<PptxMatchLocation>[]>;
    findNext(): Promise<FindMatch<PptxMatchLocation> | null>;
    findPrev(): Promise<FindMatch<PptxMatchLocation> | null>;
    clearFind(): void;
    get topVisibleSlide(): number;
    getResourceMetrics(): Promise<OoxmlResourceMetrics>;
    getSelectionContext(options?: PptxSelectionContextOptions): PptxSelectionContext | null;
    destroy(): void;
    private __privatePresence;
}
export interface PptxScrollViewerOptions extends Pick<RenderSlideOptions, 'width' | 'dpr'>, LoadOptions {
    width?: number;
    gap?: number;
    paddingTop?: number;
    paddingBottom?: number;
    paddingLeft?: number;
    paddingRight?: number;
    overscan?: number;
    enableTextSelection?: boolean;
    enableElementSelection?: boolean;
    elementHitTolerance?: number;
    onSelectionContextChange?: (context: PptxSelectionContext | null) => void;
    onContextMenu?: (event: ViewerContextMenuEvent<PptxSelectionContext>) => void;
    findHighlightColors?: FindHighlightColors;
    enableMediaPlayback?: boolean;
    mediaOverscan?: number;
    zoomMin?: number;
    zoomMax?: number;
    enableZoom?: boolean;
    refitOnResize?: boolean;
    background?: string;
    pageShadow?: string | false;
    onVisibleSlideChange?: (topIndex: number, total: number) => void;
    onScaleChange?: (scale: number) => void;
    onError?: (err: Error) => void;
    onHyperlinkClick?: (target: HyperlinkTarget) => void;
    enableHyperlinks?: boolean;
}
export type PptxSelectionContext = PptxTextSelectionContext | PptxElementContext;
export type PptxSelectionContextOptions = TextSelectionContextOptions;
export interface PptxSelectionRunLocator {
    readonly slideIndex: number;
    readonly runIndex: number;
    readonly shapeId?: string;
    readonly elementIndex?: number;
    readonly origin?: SlideElementOrigin;
}
export interface PptxSlidePoint {
    readonly x: number;
    readonly y: number;
}
export interface PptxTextRunInfo {
    elementIndex?: number;
    origin?: SlideElementOrigin;
    shapeId?: string;
    text: string;
    inShapeX: number;
    inShapeY: number;
    w: number;
    h: number;
    fontSize: number;
    font: string;
    shapeX: number;
    shapeY: number;
    shapeW: number;
    shapeH: number;
    rotation: number;
    textBodyRotation?: number;
    hyperlink?: HyperlinkTarget;
}
export interface PptxTextSelectionContext {
    readonly format: 'pptx';
    readonly kind: 'text';
    readonly text: string;
    readonly slideIndexes: readonly number[];
    readonly shapeIds: readonly string[];
    readonly runs: readonly PptxSelectionRunLocator[];
    readonly truncated: boolean;
    readonly truncationReasons: readonly ('text' | 'runs')[];
    readonly textCharacters: number;
    readonly maxTextCharacters: number;
    readonly maxRunLocators: number;
}
export class PptxViewer implements ZoomableViewer {
    static fromPresentation(canvas: HTMLCanvasElement, presentation: PptxPresentation, opts?: Omit<PptxViewerOptions, keyof LoadOptions>): Omit<PptxViewer, 'load'>;
    constructor(canvas: HTMLCanvasElement, opts?: PptxViewerOptions);
    load(source: string | ArrayBuffer): Promise<void>;
    goToSlide(index: number): Promise<void>;
    nextSlide(): Promise<void>;
    prevSlide(): Promise<void>;
    setHiddenSlideMode(mode: HiddenSlideMode): Promise<void>;
    get hiddenSlideMode(): HiddenSlideMode;
    get visibleSlideCount(): number;
    get slideIndex(): number;
    get slideCount(): number;
    getNotes(slideIndex: number): string | null;
    get canvasElement(): HTMLCanvasElement;
    getScale(): number;
    setScale(scale: number): Promise<void>;
    zoomIn(): Promise<void>;
    zoomOut(): Promise<void>;
    fitWidth(): Promise<void>;
    fitPage(): Promise<void>;
    findText(query: string, opts?: FindMatchesOptions): Promise<FindMatch<PptxMatchLocation>[]>;
    findNext(): Promise<FindMatch<PptxMatchLocation> | null>;
    findPrev(): Promise<FindMatch<PptxMatchLocation> | null>;
    clearFind(): void;
    getResourceMetrics(): Promise<OoxmlResourceMetrics>;
    getSelectionContext(options?: PptxSelectionContextOptions): PptxSelectionContext | null;
    destroy(): void;
    private __privatePresence;
}
export interface PptxViewerOptions extends Pick<RenderOptions, 'width' | 'dpr'>, LoadOptions {
    onSlideChange?: (index: number, total: number) => void;
    onError?: (err: Error) => void;
    zoomMin?: number;
    zoomMax?: number;
    onScaleChange?: (scale: number) => void;
    enableMediaPlayback?: boolean;
    enableTextSelection?: boolean;
    enableElementSelection?: boolean;
    elementHitTolerance?: number;
    onSelectionContextChange?: (context: PptxSelectionContext | null) => void;
    onContextMenu?: (event: ViewerContextMenuEvent<PptxSelectionContext>) => void;
    findHighlightColors?: FindHighlightColors;
    hiddenSlideMode?: HiddenSlideMode;
    hiddenSlideDim?: Partial<DimOptions>;
    onHyperlinkClick?: (target: HyperlinkTarget) => void;
    enableHyperlinks?: boolean;
}
export interface Presentation {
    slideWidth: number;
    slideHeight: number;
    slides: Slide[];
    defaultTextColor: string | null;
    majorFont: string | null;
    minorFont: string | null;
    hlinkColor?: string;
    folHlinkColor?: string;
}
export interface PresentationHandle {
    play(mediaPath?: string): void;
    pause(mediaPath?: string): void;
    destroy(): void;
}
export interface PresentSlideOptions extends Omit<RenderSlideOptions, 'skipMediaControls'> {
    onError?: (error: Error) => void;
}
export function readPptxTextSelectionContext(root: HTMLElement, selection: Selection | null, options?: TextSelectionContextOptions): PptxTextSelectionContext | null;
export interface Reflection {
    blur: number;
    dist: number;
    dir: number;
    stA: number;
    stPos: number;
    endA: number;
    endPos: number;
    sx: number;
    sy: number;
}
export interface RenderOptions {
    width?: number;
    defaultTextColor?: string | null;
    dpr?: number;
    majorFont?: string | null;
    minorFont?: string | null;
    hlinkColor?: string | null;
    fetchMedia?: (path: string) => Promise<Blob>;
    fetchImage?: (path: string, mimeType: string) => Promise<Blob>;
    skipMediaControls?: boolean;
}
export function renderSlide(canvas: HTMLCanvasElement | OffscreenCanvas, slide: Slide, slideWidth: number, slideHeight: number, opts?: SlideRenderOptions, onTextRun?: TextRunCallback): Promise<HTMLCanvasElement | OffscreenCanvas>;
export interface RenderSlideOptions {
    width?: number;
    dpr?: number;
    onTextRun?: TextRunCallback;
    skipMediaControls?: boolean;
    dim?: DimOptions;
}
export interface RenderSlideToBitmapOptions {
    width?: number;
    dpr?: number;
    dim?: DimOptions;
    onTextRun?: TextRunCallback;
}
export interface Rot3d {
    lat: number;
    lon: number;
    rev: number;
}
export interface Scene3d {
    camera: Camera3d;
    lightRig?: LightRig;
}
export interface SecondaryValueAxis {
    min: number | null;
    max: number | null;
    title: string | null;
    hidden: boolean;
    formatCode?: string | null;
    fontColor?: string | null;
    fontSizeHpt?: number | null;
    fontFace?: string | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    lineHidden: boolean;
    majorTickMark: string;
    minorTickMark?: string | null;
    minorGridlines?: boolean;
    minorGridlineColor?: string | null;
    minorGridlineWidthEmu?: number | null;
    minorGridlineDash?: string | null;
    majorUnit?: number | null;
    minorUnit?: number | null;
    titleFontSizeHpt?: number | null;
    titleFontBold?: boolean | null;
    titleFontColor?: string | null;
    titleFontFace?: string | null;
    titleRotation?: number | null;
    titleVerticalMode?: 'horz' | 'vert' | 'vert270' | 'wordArtVert' | 'eaVert' | 'mongolianVert' | 'wordArtVertRtl' | null;
    titleManualLayout?: ChartManualLayout | null;
}
export interface Shadow {
    color: string;
    alpha: number;
    blur: number;
    dist: number;
    dir: number;
    sx?: number;
    sy?: number;
    kx?: number;
    ky?: number;
    algn?: 'tl' | 't' | 'tr' | 'l' | 'ctr' | 'r' | 'bl' | 'b' | 'br';
    rotWithShape?: boolean;
}
export interface ShapeElement {
    type: 'shape';
    x: number;
    y: number;
    width: number;
    height: number;
    rotation: number;
    flipH: boolean;
    flipV: boolean;
    geometry: string;
    fill: Fill | null;
    stroke: Stroke | null;
    textBody: TextBody | null;
    defaultTextColor: string | null;
    custGeom: PathCmd[][] | null;
    adj: number | null;
    adj2: number | null;
    adj3: number | null;
    adj4: number | null;
    adj5: number | null;
    adj6: number | null;
    adj7: number | null;
    adj8: number | null;
    shadow: Shadow | null;
    innerShadow?: Shadow;
    glow?: Glow;
    softEdge?: SoftEdge;
    reflection?: Reflection;
    textRect?: TextRect;
    scene3d?: Scene3d;
    sp3d?: Sp3d;
    id?: string;
    name?: string;
    hyperlink?: string;
    hyperlinkAction?: string;
}
export interface Slide {
    index: number;
    slideNumber: number;
    partName?: string;
    background: Fill | null;
    elements: SlideElement[];
    elementSources?: SlideElementSource[];
    notes?: string;
    comments?: PptxComment[];
    hidden?: boolean;
    parseError?: string;
}
export type SlideElement = ShapeElement | PictureElement | TableElement | ChartElement | MediaElement;
export type SlideElementOrigin = 'master' | 'layout' | 'slide';
export interface SlideElementSource {
    origin: SlideElementOrigin;
}
export type SlideRenderOptions = RenderOptions & {
    math?: MathRenderer;
    dim?: DimOptions;
};
export interface SoftEdge {
    radius: number;
}
export interface SolidFill {
    fillType: 'solid';
    color: string;
}
export interface Sp3d {
    z?: number;
    extrusionH?: number;
    contourW?: number;
    contourClr?: string;
    extrusionClr?: string;
    prstMaterial: string;
    bevelT?: Bevel3d;
    bevelB?: Bevel3d;
}
export type SpaceLine = {
    type: 'pct';
    val: number;
} | {
    type: 'pts';
    val: number;
};
export interface Stroke {
    color: string;
    width: number;
    fill?: Exclude<Fill, {
        fillType: 'image';
    } | {
        fillType: 'none';
    }>;
    dashStyle?: string;
    customDash?: ReadonlyArray<{
        dash: number;
        space: number;
    }>;
    lineCap?: 'butt' | 'round' | 'square';
    lineJoin?: 'round' | 'bevel' | 'miter';
    miterLimit?: number;
    alignment?: 'ctr' | 'in';
    headEnd?: ArrowEnd;
    tailEnd?: ArrowEnd;
    cmpd?: string;
}
export interface TableCell {
    textBody: TextBody | null;
    fill: Fill | null;
    textColor?: string;
    borderL: Stroke | null;
    borderR: Stroke | null;
    borderT: Stroke | null;
    borderB: Stroke | null;
    diagonalTL?: Stroke | null;
    diagonalTR?: Stroke | null;
    gridSpan: number;
    rowSpan: number;
    hMerge: boolean;
    vMerge: boolean;
}
export interface TableElement {
    type: 'table';
    x: number;
    y: number;
    width: number;
    height: number;
    rotation: number;
    flipH: boolean;
    flipV: boolean;
    cols: number[];
    rows: TableRow[];
    rtl?: boolean;
}
export interface TableRow {
    height: number;
    cells: TableCell[];
}
export interface TabStop {
    pos: number;
    algn: string;
}
export interface TextBody extends TextBody__emitterCollision1 {
    rtlCol?: boolean;
    textWarp?: {
        preset: string;
        adj?: number[];
    };
    paragraphs: Paragraph[];
}
interface TextBody__emitterCollision1 {
    verticalAnchor: string;
    paragraphs: Paragraph__emitterCollision1[];
    defaultFontSize: number | null;
    defaultBold: boolean | null;
    defaultItalic: boolean | null;
    lIns: number;
    rIns: number;
    tIns: number;
    bIns: number;
    wrap: string;
    vert: string;
    autoFit: string;
    fontScale?: number | null;
    lnSpcReduction?: number | null;
    numCol?: number;
    spcCol?: number;
}
export interface TextOutline {
    width: number;
    color?: string;
}
export interface TextRect {
    x: number;
    y: number;
    width: number;
    height: number;
}
export type TextRun = TextRunData | LineBreak | EquationRun;
export type TextRunCallback = (run: PptxTextRunInfo) => void;
export interface TextRunData {
    type: 'text';
    text: string;
    bold: boolean | null;
    italic: boolean | null;
    underline: boolean;
    underlineStyle?: string;
    underlineColor?: string;
    strikethrough: boolean;
    strikeDouble?: boolean;
    fontSize: number | null;
    color: string | null;
    fontFamily: string | null;
    fontFamilyEa?: string;
    fontFamilySym?: string;
    baseline?: number;
    caps?: 'none' | 'small' | 'all';
    letterSpacing?: number;
    fieldType?: string;
    hyperlink?: string;
    hyperlinkAction?: string;
    shadow?: Shadow;
    reflection?: Reflection;
    outline?: TextOutline;
    highlight?: string;
}
export interface TextSelectionContextOptions {
    readonly maxTextCharacters?: number;
    readonly maxRunLocators?: number;
}
export interface TileInfo {
    tx: number;
    ty: number;
    sx: number;
    sy: number;
    flip: string;
    algn?: string;
}
export interface ViewerContextMenuEvent<TContext> {
    readonly originalEvent: MouseEvent;
    getContext(): Promise<TContext | null>;
}
export interface ZoomableViewer {
    getScale(): number;
    setScale(scale: number): void | Promise<void>;
    zoomIn(): void | Promise<void>;
    zoomOut(): void | Promise<void>;
    fitWidth(): void | Promise<void>;
    fitPage(): void | Promise<void>;
}
